<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PlaceSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table("places")->insert(
      [
        [
          'place_id'=> '1',
          'name'=> 'Laboratorio Moreno',
          'address'=> 'Uruguay 80',
          'city'=> 'Moreno',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Laboratorio de análisis clínicos',
          'main_img'=> 'places/1.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> false,
          'elevator'=> false,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '10',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '2',
          'name'=> 'Cóndor Clift - Pizza & Pasta',
          'address'=> 'Av. del Libertador 2',
          'city'=> 'Moreno',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Restaurante y cafetería',
          'main_img'=> 'places/2.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> false,
          'elevator'=> true,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '6',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '3',
          'name'=> 'Hotel UTHGRA de las Luces',
          'address'=> 'Adolfo Alsina 525',
          'city'=> 'CABA',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Este hotel modesto está ubicado en una casa adosada, a 3 minutos a pie de la estación de metro más cercana, a 6 minutos a pie de la Casa Rosada y a 2 km del gran teatro Colón.

          Las habitaciones sencillamente amuebladas disponen de conexión Wi-Fi gratis, TV por cable, caja fuerte y frigobar. Algunas cuentan con capacidad para 3 personas. Se ofrece servicio a la habitación.

          Se ofrece desayuno tipo bufé. Además, dispone de un bar informal, un salón y un centro de negocios.',
          'main_img'=> 'places/3.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> false,
          'elevator'=> true,
          'src_info_id'=> '3',
          'review_id'=> NULL,
          'category_id'=> '1',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '4',
          'name'=> 'Café Martínez',
          'address'=> 'Concejal Alberto Rosset 200',
          'city'=> 'Moreno',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Cafetería.',
          'main_img'=> 'places/4.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> false,
          'elevator'=> false,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '6',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '5',
          'name'=> 'Diagnóstico Tesla Moreno',
          'address'=> 'Av. Int. Pagano 2666',
          'city'=> 'Moreno',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Centro de diagnóstico por imágenes.',
          'main_img'=> 'places/5.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> true,
          'elevator'=> false,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '10',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '6',
          'name'=> 'Cyan Hotel de las Americas',
          'address'=> 'Libertad 1020',
          'city'=> 'CABA',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Situado en el corazón del barrio de Recoleta, el Cyan Hotel de las Américas de 4 estrellas ofrece amplias habitaciones con aire acondicionado a pocos metros de las populares avenidas 9 de Julio y Santa Fe. Se proporciona conexión WiFi gratuita.

          Como huésped del Cyan Hotel de las Américas, podrá caminar hasta el Obelisco, la Plaza San Martín, la Catedral Metropolitana y varios otros atractivos de Buenos Aires.

          El hotel ofrece un suntuoso desayuno bufé y otras opciones gastronómicas durante el día en el restaurante y snack bar. Además, el servicio de habitaciones está disponible las 24 horas del día.',
          'main_img'=> 'places/6.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> true,
          'elevator'=> true,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '1',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '7',
          'name'=> 'Museo Nacional de Bellas Artes',
          'address'=> 'Av. del Libertador 1473',
          'city'=> 'CABA',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'El Museo Nacional de Bellas Artes, ubicado en la Ciudad de Buenos Aires, es una de las instituciones públicas de arte más importantes de Argentina. Alberga un patrimonio sumamente diverso, que incluye más de 12 000 piezas, entre pinturas, esculturas, dibujos, grabados, textiles y objetos.',
          'main_img'=> 'places/7.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> false,
          'elevator'=> false,
          'src_info_id'=> '3',
          'review_id'=> NULL,
          'category_id'=> '2',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '8',
          'name'=> 'Unicenter',
          'address'=> 'Paraná 3745',
          'city'=> 'Martínez',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Unicenter Shopping es el centro comercial más grande de la Argentina. El shopping, que pertenece al holding chileno Cencosud, fue inaugurado el 12 de octubre de 1988, y se encuentra ubicado en la localidad de Martínez.',
          'main_img'=> 'places/8.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> true,
          'elevator'=> true,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '3',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '9',
          'name'=> 'Teatro Marechal',
          'address'=> 'Eduardo Asconapé 81',
          'city'=> 'Moreno',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Teatro Marechal es un teatro municipal ubicado en la ciudad de Moreno, provincia de Buenos Aires, Argentina.',
          'main_img'=> 'places/9.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> false,
          'assisted_access_entrance'=> true,
          'internal_circulation'=> true,
          'bathroom'=> false,
          'adult_changing_table'=> false,
          'parking'=> false,
          'elevator'=> false,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '2',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '10',
          'name'=> 'McDonald\'s',
          'address'=> 'Av. Bartolomé Mitre 2859',
          'city'=> 'Moreno',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Restaurante de comida rápida',
          'main_img'=> 'places/10.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> false,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> false,
          'elevator'=> false,
          'src_info_id'=> '2',
          'review_id'=> NULL,
          'category_id'=> '6',
          'uploaded_from_id'=> '3',
        ],
        [
          'place_id'=> '11',
          'name'=> 'Perla Norte',
          'address'=> 'Bv. Marítimo P. P. Ramos 230',
          'city'=> 'Mar del Plata',
          'province'=> 'Buenos Aires',
          'latitude'=> NULL,
          'longitude'=> NULL,
          'description'=> 'Estacionamiento prioritario, rampa de acceso (pendiente pronunciada), circulaciones garantizadas por rampas asistidas, unidades de sombra, sanitario y vestuario accesible y 4 sillas anfibias en sector público',
          'main_img'=> 'places/11.jpg',
          'alt_main_img' => 'frente del lugar',
          'access_entrance'=> true,
          'assisted_access_entrance'=> true,
          'internal_circulation'=> true,
          'bathroom'=> true,
          'adult_changing_table'=> false,
          'parking'=> true,
          'elevator'=> false,
          'src_info_id'=> '4',
          'review_id'=> NULL,
          'category_id'=> '5',
          'uploaded_from_id'=> '3',
        ]
      ]
    );
  }
}


